services:
  api:
    image: routeoptim-api
    build:
      context: ./routeOptimizerAPI/
      dockerfile: Dockerfile
    volumes:
      - ./routeOptimizerAPI/:/usr/src/app
    container_name: routeoptim-api
  app:
    image: routeoptim-front
    build:
      context: ./routeOptimizer/
      dockerfile: Dockerfile
    volumes:
      - ./routeOptimizer/:/usr/src/app
    container_name: routeoptim-front
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-routeoptim
    depends_on:
      - api
      - app

