name: Client pipeline
on: [push, pull_request]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run tests
          start: npm start
          wait-on: http://localhost:3000
      - name: gh-pages
        if: success()
        with:
          command: npm run deploy